kind: Service
apiVersion: v1
metadata:
  name: ct-diag-server-pipe
spec:
  selector:
    app: ct-diag-server-pipe
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ct-diag-server
  labels:
    app: ct-diag-server-pipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ct-diag-server-pipe
  template:
    metadata:
      labels:
        app: ct-diag-server-pipe
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: ct-diag-server-pipe
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
