version: "3.4"
services:
  postgres-test:
    image: postgres:11.7-alpine
    restart: always
    environment:
      POSTGRES_USER: ct-diag-test
      POSTGRES_PASSWORD: ct-diag-test
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "54321:5432"
